### ISSUE TITLE
3.1.0 not launching on Kodi on Android TV

### ISSUE THREAD

**Issue by krawiece** [fungus1487/xbmc-hockey-streams#11]
Player no longer launches.  Worked perfectly prior to 3.1.0.

**Comment by Swedemon** [comment]
Please post log and note Kodiak version

**Comment by krawiece** [comment]
[kodi.txt](https://github.com/fungus1487/xbmc-hockey-streams/files/46622/kodi.txt)

**Comment by krawiece** [comment]
Kodi (15.2 Git:2015-10-27-862a516). Platform: Android x86 32-bit

**Comment by krawiece** [comment]
Fixed with 3.1.1.  Thank you!
