### ISSUE TITLE
On Demand Highlights Missing

### ISSUE THREAD

**Issue by ultimateguy** [fungus1487/xbmc-hockey-streams#6]
Just wanted to thank you for this fantastic addon.

In my on demand section, there are many games for which only the full games are available, i.e. there is no condensed version or highlights version. I have made sure to tick these in the settings so they should be visible. Is there a way to fix this?

**Comment by Swedemon** [comment]
Depends on the content provided by hockeystreams.  But a related issue will be addressed once we merge philippe's addon.
