### ISSUE TITLE
Fan art not displaying

### ISSUE THREAD

**Issue by sstoveld** [fungus1487/xbmc-hockey-streams#7]
Hey there, running hockeystreams on kodi on my nvidia shield tv, app works great, but doesn't seem to display fanart. Just shows the default hockey helmet for all games instead of team logos. Any ideas? I've restarted both the plugin and my device several times as the setting says it requires a restart, but no luck

**Comment by Swedemon** [comment]
Sorry, I'm unable to replicate, so not sure the issue.
